<?php

(defined('BASEPATH')) or exit('No direct script access allowed');
/**
 * LIST OF PERMISSION
 *
 * Put all permission in this class.
 * To be loaded automatically, this class need to register
 * to $autoload['libraries'] in config/autoload.php
 *
 * <select ('const '||pm.code::Text||' ='''||pm.code::Text||''';') from xs_permission_mask pm>
 * 
 * @author Rizal.Gurning
 */
class Permission{
	const ACCOUNT_MENU_VIEW = 'ACCOUNT_MENU_VIEW';
	const ACCOUNT_PERMISSION_MASK_VIEW = 'ACCOUNT_PERMISSION_MASK_VIEW';
	const ACCOUNT_ROLE_DELETE = 'ACCOUNT_ROLE_DELETE';
	const ACCOUNT_ROLE_INSERT = 'ACCOUNT_ROLE_INSERT';
	const ACCOUNT_ROLE_PERMISSION_MASK_ASSIGN = 'ACCOUNT_ROLE_PERMISSION_MASK_ASSIGN';
	const ACCOUNT_ROLE_PERMISSION_MASK_UNASSIGN = 'ACCOUNT_ROLE_PERMISSION_MASK_UNASSIGN';
	const ACCOUNT_ROLE_PERMISSION_MASK_VIEW = 'ACCOUNT_ROLE_PERMISSION_MASK_VIEW';
	const ACCOUNT_ROLE_UPDATE = 'ACCOUNT_ROLE_UPDATE';
	const ACCOUNT_ROLE_VIEW = 'ACCOUNT_ROLE_VIEW';
	const ACCOUNT_USER_CHANGE_PASSWORD = 'ACCOUNT_USER_CHANGE_PASSWORD';
	const ACCOUNT_USER_DELETE = 'ACCOUNT_USER_DELETE';
	const ACCOUNT_USER_INSERT = 'ACCOUNT_USER_INSERT';
	const ACCOUNT_USER_ROLE_ASSIGN = 'ACCOUNT_USER_ROLE_ASSIGN';
	const ACCOUNT_USER_ROLE_UNASSIGN = 'ACCOUNT_USER_ROLE_UNASSIGN';
	const ACCOUNT_USER_ROLE_VIEW = 'ACCOUNT_USER_ROLE_VIEW';
	const ACCOUNT_USER_UPDATE = 'ACCOUNT_USER_UPDATE';
	const ACCOUNT_USER_VIEW = 'ACCOUNT_USER_VIEW';
	const CASHIER_UPDATE_DISCOUNT = 'CASHIER_UPDATE_DISCOUNT';
	const CASHIER_VIEW_CART = 'CASHIER_VIEW_CART';
	const GOOD_RECEIVE_ADJUSTMENT = 'GOOD_RECEIVE_ADJUSTMENT';
	const MASTER_CATEGORY = 'MASTER_CATEGORY';
	const MASTER_ITEM = 'MASTER_ITEM';
	const MASTER_STORE = 'MASTER_STORE';
	const MASTER_UOM = 'MASTER_UOM';
	const MASTER_USER_DELETE = 'MASTER_USER_DELETE';
	const MASTER_USER_INSERT = 'MASTER_USER_INSERT';
	const MASTER_USER_UPDATE = 'MASTER_USER_UPDATE';
	const MASTER_USER_VIEW = 'MASTER_USER_VIEW';
	const ORDER_MANAGEMENT_GOOD_RECEIVE_TS = 'ORDER_MANAGEMENT_GOOD_RECEIVE_TS';
	const ORDER_MANAGEMENT_PO = 'ORDER_MANAGEMENT_PO';
	const ORDER_MANAGEMENT_TRANSFER_STOCK = 'ORDER_MANAGEMENT_TRANSFER_STOCK';
	const ORDER_MANAGEMENT_VIEW_VENDOR_ITEM = 'ORDER_MANAGEMENT_VIEW_VENDOR_ITEM';
	const ORDER_MANAGMEENT_TRANSFER_REQ = 'ORDER_MANAGMEENT_TRANSFER_REQ';
	const PROMOTION = 'PROMOTION';
	const REPORT = 'REPORT';
	const RETURN_TO_VENDOR = 'RETURN_TO_VENDOR';
	const SALES_VIEW_DAILY_SALES = 'SALES_VIEW_DAILY_SALES';
	const STOCK_OPNAME = 'STOCK_OPNAME';
	const STOCK_TRANSFER_RECEIVE = 'STOCK_TRANSFER_RECEIVE';
	const STOCK_TRANSFER_RECEIVE_ADJUSTMENT = 'STOCK_TRANSFER_RECEIVE_ADJUSTMENT';
	const MASTER_VENDOR = 'MASTER_VENDOR';
	const MASTER_CUSTOMER = 'MASTER_CUSTOMER';
	const MASTER_VENDOR_ITEM = 'MASTER_VENDOR_ITEM';
	const BROKEN_STOCK = 'BROKEN_STOCK';
	const SYNCHRONIZE = 'SYNCHRONIZE';
}